# File: .air.toml

# Direktori utama project
root = "."

# Folder untuk binary sementara (tidak dipakai karena kita pakai `go run`)
tmp_dir = "tmp"
testdata_dir = "testdata"

[build]
  # Jalankan langsung file utama dari folder cmd/
  cmd = "go run ./cmd/main.go"
  
  # Karena pakai `go run`, kita kosongkan bin dan full_bin
  bin = ""
  full_bin = ""
  
  delay = 1000
  exclude_dir = ["tmp", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_error = false
  follow_symlink = false
  exclude_unchanged = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  silent = false
  time = false

[misc]
  clean_on_exit = false

[proxy]
  enabled = false
  app_port = 0
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
